--- #ansible playbook start with three dash
-
  hosts: worker #target where we will run the playbook
  vars:
    motd_centos: "Welcome to ansible HCL\n"
  tasks:
    - name: install apache service
      yum:
        name: ['vsftpd', 'httpd', 'postfix','dovecot', 'firewalld']
        state: latest
      notify: install packages
    - name: start and enable httpd service
      service:
        name: httpd
        enabled: true
        state: started
    - name: start and enabled firewalld
      service: 
        name: firewalld
        enabled: true
        state: started
    - name: add a rule http in your firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
    - name: create a simple html page. 
      copy:
        content: "Welcome to ansible learning\n"
        dest: /var/www/html/index.html
    - name: Define web server name
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerName www.client1.example.com:80
        insertafter: "#ServerName"
    - name: update the entry in the host file /etc/host
      lineinfile:
        path: /etc/hosts
        line: 192.168.0.22 www.client1.example.com
  handlers:
    - name: install packages
      debug:
        msg: all the packages are installed
